version: '3.8'

services:

  # Redis Configuration
  redis:
    image: redis:7-alpine
    container_name: radar_licitacoes_redis
    restart: always
    ports:
      - "6380:6379" # 6380 no host para não conflitar com outro projeto

  # Database Configuration
  postgres:
    image: postgres:15-alpine
    container_name: radar_licitacoes_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: radar_licitacoes
    ports:
      - "5433:5432" # 5433 no host para não conflitar com outro projeto
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # API configuration
  api:
    build: .
    container_name: radar_licitacoes_api
    depends_on:
      - postgres
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/radar_licitacoes
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 123

volumes:
  postgres-data:
